trigger: none
pr:
  - master
    
pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'x86'
  buildConfiguration: 'Release'

steps:
- checkout: self
  persistCredentials: true

- task: gitversion/setup@1
  displayName: 'Install GitVersion'
  inputs:
    versionSpec: '5.x'

- task: gitversion/execute@1
  displayName: 'Determine Version'
  inputs:
    updateAssemblyInfo: true

- task: PowerShell@2
  displayName: Update version in the vsix manifest
  inputs:
    filePath: 'MarkMpn.Sql4Cds.SSMS\update-version.ps1'
    arguments: '$(assemblySemVer)'
    pwsh: true

- task: DotNetCoreCLI@2
  displayName: dotnet restore
  inputs:
    command: restore
    projects: '**/*.csproj'
    feedsToUse: 'select'
    includeNuGetOrg: true

- task: VSBuild@1
  displayName: Build
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    msbuildArgs: '/p:DeployExtension=false'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    testAssemblyVer2: |
      **/MarkMpn.*.Tests.dll
      !**\obj\**
  
- task: NodeTool@0
  displayName: Install Node.js
  inputs:
    versionSpec: '20.x'

- script: |
    call npm --no-git-tag-version version $(GitVersion.SemVer)
    call npm i -g vsce
    call git config --global url."https://github".insteadOf ssh://git@github
    call git config --global url."https://github.com/".insteadOf git@github.com:
    call yarn install
    call gulp build
  displayName: Build ADS extension
  workingDirectory: '$(Build.SourcesDirectory)\AzureDataStudioExtension'
